title: Votre Conseiller Numérique
baseURL: /
params:
  layout_type: boxed
  style: classic
  palette: blue
  mode: light
  base_font: sans-serif
  header:
    type: header
    template: header
    title: VotreConseillerNumerique.com
    logo_alt: Alyvia logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: Ce que nous faisons !
        url: /faq
        style: link
      - label: Offres et tarifs
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: false
        type: action
        url: /offres-et-tarifs
      - type: action
        template: action
        label: Qui sommes-nous ?
        url: /about
        style: link
      - type: action
        template: action
        label: Contactez-nous
        url: /contact
        style: link
    has_secondary_nav: false
    has_anncmnt: false
  footer:
    type: footer
    template: footer
    logo: images/logo.svg
    logo_alt: Alyvia logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: Qui sommes nous ?
        url: /about
        style: link
      - type: action
        template: action
        label: Ce que nous faisons !
        url: /faq
        style: link
      - type: action
        template: action
        label: Contactez-nous
        url: /contact
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        template: action
        label: Offres et tarifs
        url: /offres-et-tarifs
        style: link
      - type: action
        template: action
        label: Terms & Conditions
        url: /terms-conditions
        style: link
      - type: action
        template: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: Facebook
        url: 'https://www.facebook.com/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=personal&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://votreconseillernum.netlify.app/'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
